### ISSUE TITLE
Non-UTF-8 code starting with '\xe2'

### ISSUE THREAD

**Issue by pivic** [VikParuchuri/marker#10]
I hope I've managed to fulfill the prerequisites, but when I try to convert a couple of different files, I get an error message. I'm running Manjaro btw (a version of Arch Linux):

> SyntaxError: Non-UTF-8 code starting with '\xe2' in file /home/niklas/Downloads/x.pdf on line 2, but no encoding declared; see https://peps.python.org/pep-0263/ for details

Any help would be appreciated. Cheers and many thanks for making and sharing this software!

**Comment by VikParuchuri** [comment]
I have not seen this issue, and haven't heard back, so closing.  Feel free to repost if needed.
