### ISSUE TITLE
Missing config.yml ?

### ISSUE THREAD

**Issue by jstjoe** [VikParuchuri/marker#117]
I just installed v2 via pip, and when I try to run `marker /input /output` I get this error:

`[-] Could not find /Users/joe/Code/pdfprep/config.yml.`

The route is my working directory. I searched through the repo and didn't find a config.yml example. Sorry if I missed something obvious, I'm excited to try v2 :)

**Comment by VikParuchuri** [comment]
Marker doesn't need a config.yml file.  I haven't seen this error, either. I'm guessing this is something else on your system, but I'm not sure what it could be.

**Comment by jstjoe** [comment]
Appreciate the response. I'll test in different environments and report back if I get stuck. Will close for now.

**Comment by joeamroo** [comment]
DId you ever figure out what the problem was?

**Comment by sagaruprety** [comment]
I had this same error, then I realised that I also had 'marker' library installed. Mistakenly I had installed 'marker' instead of 'marker-pdf' via pip. Perhaps it is an earlier version of marker-pdf. When I uninstalled 'marker', I no longer had this error.
