### ISSUE TITLE
I tested it and the speed is very slow. Can it be optimized? It seems that it cannot meet the online needs.

### ISSUE THREAD

**Issue by xuboot** [VikParuchuri/marker#118]
I tested it and the speed is very slow. Can it be optimized? It seems that it cannot meet the online needs.

**Comment by VikParuchuri** [comment]
To speed it up, you can:

- Use tesseract instead of surya for OCR if you're on CPU (surya OCR is slow on CPU)
- Use GPU
- Parallelize with marker (use more workers)

I need to quant + compile the models, which will speed things up.

**Comment by xuboot** [comment]
@VikParuchuri "I need to quant + compile the models, which will speed things up" Will this version be released

**Comment by VikParuchuri** [comment]
Yes, hoping to get some time to do that
