### ISSUE TITLE
Cannot uninstall TBB

### ISSUE THREAD

**Issue by RUANRui-ECON** [VikParuchuri/marker#120]
I am using win11 and trying to install marker-pdf. 
I run "pip install marker-pdf", but get "cannot uninstall tbb " error.

**Comment by arunpatro** [comment]
I am installing on mac and failing:

```
INFO: pip is still looking at multiple versions of marker-pdf to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install marker-pdf==0.1.0, marker-pdf==0.1.1, marker-pdf==0.1.2, marker-pdf==0.1.3, marker-pdf==0.2.1, marker-pdf==0.2.2, marker-pdf==0.2.4 and marker-pdf==0.2.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    marker-pdf 0.2.5 depends on ray<3.0.0 and >=2.20.0
    marker-pdf 0.2.4 depends on ray<3.0.0 and >=2.20.0
    marker-pdf 0.2.2 depends on ray<3.0.0 and >=2.20.0
    marker-pdf 0.2.1 depends on ray<3.0.0 and >=2.20.0
    marker-pdf 0.1.3 depends on ray<3.0.0 and >=2.7.1
    marker-pdf 0.1.2 depends on ray<3.0.0 and >=2.7.1
    marker-pdf 0.1.1 depends on ray<3.0.0 and >=2.7.1
    marker-pdf 0.1.0 depends on ray<3.0.0 and >=2.7.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by RUANRui-ECON** [comment]
the details of "cannot uninstall TBB' is following:
Cannot uninstall 'TBB'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by RUANRui-ECON** [comment]
> I am installing on mac and failing:
> 
> ```
> INFO: pip is still looking at multiple versions of marker-pdf to determine which version is compatible with other requirements. This could take a while.
> ERROR: Cannot install marker-pdf==0.1.0, marker-pdf==0.1.1, marker-pdf==0.1.2, marker-pdf==0.1.3, marker-pdf==0.2.1, marker-pdf==0.2.2, marker-pdf==0.2.4 and marker-pdf==0.2.5 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     marker-pdf 0.2.5 depends on ray<3.0.0 and >=2.20.0
>     marker-pdf 0.2.4 depends on ray<3.0.0 and >=2.20.0
>     marker-pdf 0.2.2 depends on ray<3.0.0 and >=2.20.0
>     marker-pdf 0.2.1 depends on ray<3.0.0 and >=2.20.0
>     marker-pdf 0.1.3 depends on ray<3.0.0 and >=2.7.1
>     marker-pdf 0.1.2 depends on ray<3.0.0 and >=2.7.1
>     marker-pdf 0.1.1 depends on ray<3.0.0 and >=2.7.1
>     marker-pdf 0.1.0 depends on ray<3.0.0 and >=2.7.1
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
> ```

many thx!
But the details of "cannot uninstall TBB' is following:
Cannot uninstall 'TBB'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by VikParuchuri** [comment]
> I am installing on mac and failing:
> 
> ```
> INFO: pip is still looking at multiple versions of marker-pdf to determine which version is compatible with other requirements. This could take a while.
> ERROR: Cannot install marker-pdf==0.1.0, marker-pdf==0.1.1, marker-pdf==0.1.2, marker-pdf==0.1.3, marker-pdf==0.2.1, marker-pdf==0.2.2, marker-pdf==0.2.4 and marker-pdf==0.2.5 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     marker-pdf 0.2.5 depends on ray<3.0.0 and >=2.20.0
>     marker-pdf 0.2.4 depends on ray<3.0.0 and >=2.20.0
>     marker-pdf 0.2.2 depends on ray<3.0.0 and >=2.20.0
>     marker-pdf 0.2.1 depends on ray<3.0.0 and >=2.20.0
>     marker-pdf 0.1.3 depends on ray<3.0.0 and >=2.7.1
>     marker-pdf 0.1.2 depends on ray<3.0.0 and >=2.7.1
>     marker-pdf 0.1.1 depends on ray<3.0.0 and >=2.7.1
>     marker-pdf 0.1.0 depends on ray<3.0.0 and >=2.7.1
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
> ```

The issue here is python 3.12 .  Ray doesn't support it yet, but will in a few weeks.  You need 3.11.

**Comment by VikParuchuri** [comment]
> I am using win11 and trying to install marker-pdf. I run "pip install marker-pdf", but get "cannot uninstall tbb " error.

I haven't seen this error.  Maybe make a virtualenv and try installing marker in it?

**Comment by gmotta** [comment]
FYI, I had the same issue in MacOS and I fixed it by manually installing Ray.

**Comment by VikParuchuri** [comment]
This should be fixed now - marker no longer needs ray.
