### ISSUE TITLE
why remove epub and mobi convert?

### ISSUE THREAD

**Issue by epic1268** [VikParuchuri/marker#126]
why remove epub and mobi conver? 
Commit: https://github.com/VikParuchuri/marker/commit/7f18bb9a8f65fcfc0212898ab8b9a787ed303281

**Comment by VikParuchuri** [comment]
Not necessary, it is easy to convert epub/mobi to html, then to markdown without going through marker.

**Comment by nhan000** [comment]
So it doesn't work with EPUB anymore right? The Readme doc still lists EPUB as a supported format so I think you need to update that.

**Comment by jonathanmach** [comment]
> So it doesn't work with EPUB anymore right? The Readme doc still lists EPUB as a supported format so I think you need to update that.

@VikParuchuri, is that the case? I also assumed it works w/ epub based on the readme / documentation.
