### ISSUE TITLE
Is it possible to set using CUDA:1 or something else?

### ISSUE THREAD

**Issue by Watterry** [VikParuchuri/marker#140]
I tried to use CUDA:1 or other device because my CUDA:0 is taken by other application. I tried to change "cuda" to "cuda:1" in all script but it didn't worked.

Is it possible to do this?

**Comment by VikParuchuri** [comment]
Just set `CUDA_VISIBLE_DEVICES=1` as an env var, and set `TORCH_DEVICE=cuda`
