### ISSUE TITLE
What should I do if I want to replace the OCR model

### ISSUE THREAD

**Issue by Lobskodax** [VikParuchuri/marker#153]
Hi, @VikParuchuri . I found that the Surya model has poor recognition rate for Chinese characters and Chinese layout. If I want to replace it with another model, how should I do?

**Comment by VikParuchuri** [comment]
Can you send me an example pdf?  You would have to modify the code to change the layout model.  For the OCR, you can use tesseract (see the README).

**Comment by Lobskodax** [comment]
Thank you for your reply. I have uploaded the sample PDF and the generated MD preview image. Due to the unique nature of Chinese characters, both Surya and Tesseract have low support for them, such as poor recognition accuracy of Chinese characters and poor layout positioning. So I hope to replace it with a specific Chinese ocr and layout model. 
[公式.pdf](https://github.com/user-attachments/files/15516333/default.pdf)
<img width="792" alt="Snipaste_2024-06-01_00-26-14" src="https://github.com/VikParuchuri/marker/assets/57852107/3fa94813-38a0-4336-8cc0-be5139286370">

**Comment by Lobskodax** [comment]
This is the meta.json file of the above reply.
{
    "languages": [
        "zh"
    ],
    "filetype": "pdf",
    "toc": [],
    "pages": 1,
    "ocr_stats": {
        "ocr_pages": 1,
        "ocr_failed": 0,
        "ocr_success": 1,
        "ocr_engine": "surya"
    },
    "block_stats": {
        "header_footer": 0,
        "code": 0,
        "table": 0,
        "equations": {
            "successful_ocr": 2,
            "unsuccessful_ocr": 0,
            "equations": 2
        }
    },
    "postprocess_stats": {
        "edit": {}
    }
}
