### ISSUE TITLE
Enhancement: use tabula to extract table data more precisely

### ISSUE THREAD

**Issue by vulcano9** [VikParuchuri/marker#156]
Dear Mr. Paruchuri,

thank you for this wonderful tool.

Is it possible to integrate [tabula](https://github.com/tabulapdf/tabula) into marker to extract tables with higher precision?
There is a python wrapper available: [tabula-py](https://github.com/chezou/tabula-py).
The accuracy of column detection in tabula is very good, while in marker it is less accurate.
On the other hand tabula has the problem that it utilizes automatic table recognition, but this is often inaccurate (in my tests, the first row is often cut off).
As I understand it, surya recognizes the table borders, so these coordinates would just need to be passed to tabula.
The best of both worlds would be to use the table recognition by marker and the conversion of the tables by tabula.
Tabula outputs a dataframe or a CSV file.
The dataframe or csv would then still need to be converted to Markdown.

What do you think of this idea?

**Comment by VikParuchuri** [comment]
I am interested in improving table detection, but incorporating tabula won't work because it has a complicated dependency chain (needs Java), and isn't actively maintained.
