### ISSUE TITLE
Page Range feature

### ISSUE THREAD

**Issue by krainboltgreene** [VikParuchuri/marker#16]
It would be extremely helpful to be able to target a specific set of pages for slice converting but also for updating previous attempts at converting (say for a page that was incorrectly or poorly converted).

I would imagine the syntax as (for a document that is 26 pages long):

```
python convert_single.py --page-range 1,10 a.pdf b.md
```

This would convert pages: 1,2,3,4,5,6,7,8,9,10

```
python convert_single.py --page-range 5,6 a.pdf b.md
```

This would convert pages: 5,6

```
python convert_single.py --page-range 24, a.pdf b.md
```

This would convert pages: 24,25,26

```
python convert_single.py --page-range -4,15 a.pdf b.md
```

This would convert pages: 23,24,25,26,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15

**Comment by krainboltgreene** [comment]
I can contribute this with some minor guidance.

**Comment by VikParuchuri** [comment]
This wouldn't be hard to add.  You can look at the `max_pages` flag as an example.  Basically it's passed into [this function](https://github.com/VikParuchuri/marker/blob/master/marker/extract_text.py#L102) to restrict the page count.  You could instead pass in an array of page numbers.
