### ISSUE TITLE
Markdown sublists (lists of lists of lists)

### ISSUE THREAD

**Issue by thetrebor** [VikParuchuri/marker#19]
First off, this is nearly magical.  Thank you.

Second, there appears to be one issue where nested lists don't work properly.
[test.md](https://github.com/VikParuchuri/marker/files/13532506/test.md)
[611-mentally-ill-persons-12-21-2020.pdf](https://github.com/VikParuchuri/marker/files/13532508/611-mentally-ill-persons-12-21-2020.pdf)

You'll notice it does 2 levels of list properly, but in section .06 where it gets very nested it breaks down.
If you can point me to the right place in your code I'd be happy to try to figure it out and send you a PR. 
It looks like it would just need to prepend 4 spaces per indent, for list items but a quick look didn't indicate where you were detecting that

**Comment by VikParuchuri** [comment]
Thanks, I appreciate the report! I don't have specific handling for lists yet, it just uses the spacing in the document.  You'd need to add in some special handling, like exists for tables - https://github.com/VikParuchuri/marker/blob/master/marker/cleaners/table.py .  Basically, grab all the contiguous list items, then indent the subitems as needed.

**Comment by thetrebor** [comment]
Bro, the data structure in your blocks is impenetrable and this is really hard to debug.
The functions all have side effects and it's hard to tell what does what to what and how the structure changes over the execution.  I really want to contribute but I've spent two days and can't get through the side effects or how the objects are nested and grouped.

I can handle the business logic of nested lists if you can get me a properly set up cleaner file that has the data I can loop through

**Comment by VikParuchuri** [comment]
Hey, I'd be happy for any contributions here.  If you want to discuss more, feel free to ping me on Discord - https://discord.gg//KuZwXNGnfH .  Happy to chat through the data structures and mutations.  It could use a refactor for sure, but I don't think it is completely impenetrable :)
