### ISSUE TITLE
Can it process images in pdf?

### ISSUE THREAD

**Issue by biandh** [VikParuchuri/marker#2]

**Comment by VikParuchuri** [comment]
It will skip the images currently.  It's possible to save the images separately and embed them into the markdown, though - what's your usecase for the images?

**Comment by DamonsJ** [comment]
I also think it is better to process image and table , like mathpix.

**Comment by VikParuchuri** [comment]
It will extract tables, just not images.  Can you tell me more about what you're using the images for?

**Comment by DamonsJ** [comment]
sometimes, you need image to illustrate the pointview in your pdf
ex, if you are working on compute graphics there are many graphs and images in paper and you want to collect it in you own note.

**Comment by Hambaobao** [comment]
We really need this feature.🔥Does anyone know if there are any alternatives that can replace this project?

**Comment by yachty66** [comment]
i just tried [groundingdino[(https://github.com/IDEA-Research/GroundingDINO) for trying to draw bounding boxes around the figures to then extract them. bad results. i wonder how far you can get by fine-tuning groundingdino for this task.

**Comment by tungsten106** [comment]
It is possible to use fitz/PyMuPDF to extract image at each page (just not at the **exact position** like docx files), save it to a position and label it as markdown format with the safe path.

**Comment by VikParuchuri** [comment]
If anyone wants to contribute this with a PR, I'd be very excited to review.  I'm working on improving some of the base models and making marker fully open (it's noncommercial right now due to nougat and layoutlmv3 licensing), so I don't have bandwidth to take the image project on at the moment.  

The segmentation model identifies image positions, so it may be possible to extract images using that, and embed them in the right spot.

**Comment by yachty66** [comment]
> It is possible to use fitz/PyMuPDF to extract image at each page (just not at the **exact position** like docx files), save it to a position and label it as markdown format with the safe path.

no you cannot really - at least its not good. fitz/PyMuPDF is not getting all images

**Comment by 7flash** [comment]
Yes please. My use case: pdf => markdown => html => png images

**Comment by VikParuchuri** [comment]
I'm training a model to extract images - this will be integrated into marker

**Comment by VikParuchuri** [comment]
Image extraction will be coming in the next version (should be shipped in the next 2 weeks).

**Comment by VikParuchuri** [comment]
Just added this into the dev branch - https://github.com/VikParuchuri/marker/pull/111 .  I'm going to close this issue, since the feature will land in master soon (next few days).
