### ISSUE TITLE
[feature request] Roadmap for Converting PDFs to Complex Markup Languages (AsciiDoc, TeX/LaTeX, HTML+CSS)

### ISSUE THREAD

**Issue by Foadsf** [VikParuchuri/marker#206]
I've been exploring Marker's capabilities and am genuinely impressed with its performance in converting PDFs to Markdown. As someone who often works with various markup languages, I have a feature request that could benefit a wide range of users.

It would be great if we could have a roadmap towards enabling Marker to convert PDFs into more complex markup languages such as AsciiDoc, TeX/LaTeX, or even HTML+CSS. This feature would greatly enhance Marker's versatility, making it a go-to tool for a variety of documentation and publishing needs.

I understand this is an ambitious goal, though having a clear vision and incremental milestones could make it achievable. Accurately converting PDFs to these formats would be a significant step forward in document conversion technology.

**Comment by VikParuchuri** [comment]
You should be able to postprocess to convert from markdown to these formats relatively easily (html very straightforward).  I'm not planning on including this support in the core marker, since there are already very good tools, like pandoc, for doing this.
