### ISSUE TITLE
access is denied

### ISSUE THREAD

**Issue by devpowerplatform** [VikParuchuri/marker#208]
after installing all required packages, I tried to convert one pdf file into markdown. I got this error message. 

(pdf_parse311) C:\temp\pdf_parse>marker_single ./pdf/if10244.pdf ./out --batch_multiplier 2 --max_pages 10 --langs English
Access is denied.

i'm a windows user.

**Comment by VikParuchuri** [comment]
Seems like a permissions issue on your side, not related to marker
