### ISSUE TITLE
 Number of processes must be at least 1

### ISSUE THREAD

**Issue by Degfy** [VikParuchuri/marker#211]
run Command like this：
```bash
$ marker '/data/home/aiunicorn_zhanghe/st-relate/sgcc-tech-standard-dedup/' ./doc  --workers 4 --max 10
```
get error:
```
Loaded detection model vikp/surya_det2 on device cuda with dtype torch.float16
Loaded detection model vikp/surya_layout2 on device cuda with dtype torch.float16
Loaded reading order model vikp/surya_order on device cuda with dtype torch.float16
Loaded recognition model vikp/surya_rec on device cuda with dtype torch.float16
Loaded texify model to cuda with torch.float16 dtype
Converting 0 pdfs in chunk 1/1 with 0 processes, and storing in /extend/ai/works/converted-standard/doc
Traceback (most recent call last):
  File "/extend/ai/miniconda3/envs/marker-pdf/bin/marker", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/convert.py", line 133, in main
    with mp.Pool(processes=total_processes, initializer=worker_init, initargs=(model_lst,)) as pool:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

**Comment by Degfy** [comment]
marker_single '****.pdf' ./  --batch_multiplier 2

Loaded detection model vikp/surya_det2 on device cuda with dtype torch.float16
Loaded detection model vikp/surya_layout2 on device cuda with dtype torch.float16
Loaded reading order model vikp/surya_order on device cuda with dtype torch.float16
Loaded recognition model vikp/surya_rec on device cuda with dtype torch.float16
Loaded texify model to cuda with torch.float16 dtype
Detecting bboxes: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.12it/s]
Recognizing Text: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:06<00:00,  1.71s/it]
Detecting bboxes: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.81s/it]
Finding reading order:   0%|                                                                                                                 | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/extend/ai/miniconda3/envs/marker-pdf/bin/marker_single", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/convert_single.py", line 28, in main
    full_text, images, out_meta = convert_single_pdf(fname, model_lst, max_pages=args.max_pages, langs=langs, batch_multiplier=args.batch_multiplier, start_page=args.start_page)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/marker/convert.py", line 113, in convert_single_pdf
    surya_order(doc, pages, order_model, batch_multiplier=batch_multiplier)
  File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/marker/layout/order.py", line 33, in surya_order
    order_results = batch_ordering(images, bboxes, order_model, processor, batch_size=int(get_batch_size() * batch_multiplier))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/surya/ordering.py", line 68, in batch_ordering
    return_dict = model(
                  ^^^^^^
  File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/surya/model/ordering/encoderdecoder.py", line 38, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/transformers/models/donut/modeling_donut_swin.py", line 965, in forward
    embedding_output, input_dimensions = self.embeddings(
                                         ^^^^^^^^^^^^^^^^
  File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: VariableDonutSwinEmbeddings.forward() got an unexpected keyword argument 'interpolate_pos_encoding'

**Comment by Degfy** [comment]
The problem has been solved, refer to issues  #185  , pdf files cannot be placed in subdirectories

**Comment by Degfy** [comment]
> marker_single '****.pdf' ./ --batch_multiplier 2
> 
> Loaded detection model vikp/surya_det2 on device cuda with dtype torch.float16 Loaded detection model vikp/surya_layout2 on device cuda with dtype torch.float16 Loaded reading order model vikp/surya_order on device cuda with dtype torch.float16 Loaded recognition model vikp/surya_rec on device cuda with dtype torch.float16 Loaded texify model to cuda with torch.float16 dtype Detecting bboxes: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00, 1.12it/s] Recognizing Text: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:06<00:00, 1.71s/it] Detecting bboxes: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00, 4.81s/it] Finding reading order: 0%| | 0/1 [00:00<?, ?it/s] Traceback (most recent call last): File "/extend/ai/miniconda3/envs/marker-pdf/bin/marker_single", line 8, in sys.exit(main()) ^^^^^^ File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/convert_single.py", line 28, in main full_text, images, out_meta = convert_single_pdf(fname, model_lst, max_pages=args.max_pages, langs=langs, batch_multiplier=args.batch_multiplier, start_page=args.start_page) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/marker/convert.py", line 113, in convert_single_pdf surya_order(doc, pages, order_model, batch_multiplier=batch_multiplier) File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/marker/layout/order.py", line 33, in surya_order order_results = batch_ordering(images, bboxes, order_model, processor, batch_size=int(get_batch_size() * batch_multiplier)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/surya/ordering.py", line 68, in batch_ordering return_dict = model( ^^^^^^ File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl return self._call_impl(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl return forward_call(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/surya/model/ordering/encoderdecoder.py", line 38, in forward encoder_outputs = self.encoder( ^^^^^^^^^^^^^ File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl return self._call_impl(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl return forward_call(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/transformers/models/donut/modeling_donut_swin.py", line 965, in forward embedding_output, input_dimensions = self.embeddings( ^^^^^^^^^^^^^^^^ File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl return self._call_impl(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/extend/ai/miniconda3/envs/marker-pdf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl return forward_call(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: VariableDonutSwinEmbeddings.forward() got an unexpected keyword argument 'interpolate_pos_encoding'

refer to issues # 209，

pip install transformers==4.41.2

**Comment by VikParuchuri** [comment]
Typeerror fixed by https://github.com/VikParuchuri/marker/pull/213
