### ISSUE TITLE
JSON output?

### ISSUE THREAD

**Issue by micthiesen** [VikParuchuri/marker#24]
Just wondering if this could be used to output the parsed content in a structured output, a la JSON. I tried looking at the internals and couldn't see if this was easily possible, or if you go directly from PDF to markdown.

**Comment by VikParuchuri** [comment]
Yes, the intermediate representations are just pydantic objects, so you could easily dump them to json.  You would essentially get a list of text, block type (formula, etc), and coordinates per page.  Right after this line is probably the best point to dump out json - https://github.com/VikParuchuri/marker/blob/master/marker/convert.py#L154
