### ISSUE TITLE
CONFUSING! About Optional: OCRMyPDF

### ISSUE THREAD

**Issue by ckgithub2019** [VikParuchuri/marker#248]
1. What's the relation between OCRMyPDF and marker-pdf?
2. If I install OCRMyPD and related packages, what could it do?
3. If I only install OCRMyPD, do I need to install marker-pdf?
4. Why does it need to run apt-get install ocrmypdf and run pip install ocrmypdf?
"""
Run apt-get install ocrmypdf
Install ghostscript > 9.55 by following [these instructions](https://ghostscript.readthedocs.io/en/latest/Install.html) or running scripts/install/ghostscript_install.sh.
Run pip install ocrmypdf
"""

**Comment by thebigboss9018** [comment]
marker doesn't do the OCR itself, it depends on Surya by default or  OCRMyPDF as another option. 

If you use Surya, you dont need to install ocrmypdf.

**Comment by ckgithub2019** [comment]
> marker doesn't do the OCR itself, it depends on Surya by default or OCRMyPDF as another option.
> 
> If you use Surya, you dont need to install ocrmypdf.

Thanks. When or in what scenarios is OCR installation necessary?

**Comment by VikParuchuri** [comment]
It's not necessary - it's an option if you want to use tesseract for some reason (I wouldn't recommend it)
