### ISSUE TITLE
Absolut Gobboly Goo Output Markdown

### ISSUE THREAD

**Issue by lucaspeyrin** [VikParuchuri/marker#277]
I'm working with confidential pdfs, but when trying to convert to markdown a 5 page very NORMAL pdf, and after marker working perfectly for 50 others, I don't know why but for one pdf it outputs:

>  /HV LQVWDOODWLRQV GRLYHQW rWUH FRQoXHV SRXU SHUPHWWUH O¶REVHUYDWLRQ GHV DFWLYLWpV GH
 SURGXFWLRQGHSXLVO¶H[WpULHXUGHV]RQHVGHFODVVH$HW%SDUH[HPSOHGHVIHQrWUHVRX
 GHV FDPpUDV DYHF XQH YXH FRPSOqWH GH OD ]RQH HW GHV SURFpGpV SHUPHWWDQW DLQVL O¶REVHUYDWLRQHWODVXUYHLOODQFHVDQVHQWUHU&HWWHH[LJHQFHGRLWrWUHSULVHHQFRPSWHORUV
 GH OD FRQFHSWLRQ GH QRXYHOOHV LQVWDOODWLRQV RX ORUV GH OD UpQRYDWLRQ G¶LQVWDOODWLRQV
 H[LVWDQWHV

## 7(&+12/2*,(6%$55,Ê5(6

 /HVLVRODWHXUVRXOHV5$%6TXLVRQWGHVWHFKQRORJLHVGLIIpUHQWHVDLQVLTXHOHVSURFpGpV
 DVVRFLpVGRLYHQWrWUHFRQoXVSRXUDVVXUHUODSURWHFWLRQSDUODVpSDUDWLRQGHOD]RQHGH
 FODVVH$GHO¶HVSDFHHQYLURQQDQW/HVULVTXHVLQGXLWVORUVGHO¶LQWURGXFWLRQRXGXUHWUDLW
 GHVDUWLFOHVSHQGDQWOHSURFpGpGHIDEULFDWLRQGRLYHQWrWUHUpGXLWVHWDFFRPSDJQpVSDU GHV WHFKQRORJLHV GH WUDQVIHUW RX GHV V\VWqPHV UREXVWHV YDOLGpV TXL SUpYLHQQHQW OD
 FRQWDPLQDWLRQHWVRQWDSSURSULpVSRXUODWHFKQRORJLHFRQFHUQpH

 /DFRQFHSWLRQGHODWHFKQRORJLHHWGHVSURFpGpVXWLOLVpVGRLWJDUDQWLUTXHGHVFRQGLWLRQV
 DSSURSULpHV VRQW PDLQWHQXHV GDQV OD ]RQH FULWLTXH DILQ GH SURWpJHU OH SURGXLW H[SRVp SHQGDQWOHVRSpUDWLRQV

L ,VRODWHXUV

D /DFRQFHSWLRQGHVLVRODWHXUVRXYHUWVGRLWJDUDQWLUGHVFRQGLWLRQVGHFODVVH$DYHF
XQH SURWHFWLRQ SDU GH O¶DLU SULPDLUH GDQV OD ]RQH FULWLTXH HW XQ IOX[ G¶DLU
XQLGLUHFWLRQQHO TXL DX FRXUV GH ODIDEULFDWLRQEDOD\H OHV SURGXLWV H[SRVpV SXLV V¶pYDFXH
E /DFRQFHSWLRQGHVLVRODWHXUVIHUPpVGRLWJDUDQWLUGHVFRQGLWLRQVGHFODVVH$DYHF
XQH SURWHFWLRQ DGpTXDWH SRXU OHV SURGXLWV H[SRVpV SHQGDQW OH SURFpGp /HIOX[
G¶DLUSHXWQHSDVrWUHHQWLqUHPHQWXQLGLUHFWLRQQHOGDQVOHVLVRODWHXUVIHUPpVR
GHVRSpUDWLRQVVLPSOHVVRQWHIIHFWXpHV7RXWHIRLVWRXWIOX[G¶DLUWXUEXOHQWQHGRLW
SDVDXJPHQWHUOHULVTXHGHFRQWDPLQDWLRQGXSURGXLWH[SRVp/RUVTXHGHVOLJQHV GHIDEULFDWLRQVRQWLQVWDOOpHVGDQVGHVLVRODWHXUVIHUPpVOHVFRQGLWLRQVGHFODVVH
$ GRLYHQW rWUH DVVXUpHV DYHF XQH SURWHFWLRQ SDU GH O¶DLU SULPDLUH GDQV OD ]RQH
FULWLTXHHWSDUXQIOX[G¶DLUXQLGLUHFWLRQQHOTXLDXFRXUVGHODIDEULFDWLRQEDOD\HOHV
SURGXLWVH[SRVpVSXLVV¶pYDFXH
F /HV LVRODWHXUV j SUHVVLRQ QpJDWLYH QH GRLYHQW rWUH XWLOLVpV TXH ORUVTXH OH
FRQILQHPHQW GX SURGXLW HVW MXJp HVVHQWLHO SDU H[HPSOH OHV SURGXLWV UDGLRSKDUPDFHXWLTXHVHWTXHGHVPHVXUHVGHPDLWULVHGHV ULVTXHV VSpFLILTXHV VRQWDSSOLTXpHVSRXUV¶DVVXUHUTXHOD]RQHFULWLTXHQ¶HVWSDVFRPSURPLVH

## Ll 5$%6

/DFRQFHSWLRQGX5$%6GRLWJDUDQWLUGHVFRQGLWLRQVGHFODVVH$DYHFXQIOX[G¶DLU
XQLGLUHFWLRQQHOHWXQHSURWHFWLRQSDUGHO¶DLUSULPDLUHGDQVOD]RQHFULWLTXH8QIOX[
G¶DLUSRVLWLIGHOD]RQHFULWLTXHYHUVO¶HQYLURQQHPHQWLPPpGLDWGRLWrWUHPDLQWHQX

 
 /¶HQYLURQQHPHQWGHOD]RQHRVHVLWXHO¶LVRODWHXURXOH5$%6GRLWJDUDQWLUTXHOHULVTXH
 GHWUDQVIHUWGHFRQWDPLQDQWVHVWPLQLPLVp L ,VRODWHXUV

D /¶HQYLURQQHPHQW R VH VLWXHQW OHV LVRODWHXUV RXYHUWV GRLW JpQpUDOHPHQW
 FRUUHVSRQGUH  j OD FODVVH & DX PLQLPXP /¶HQYLURQQHPHQW R VH VLWXHQW OHV LVRODWHXUV IHUPpV GRLW FRUUHVSRQGUH DX PLQLPXP j OD FODVVH ' /D GpFLVLRQ UHODWLYHjODFODVVLILFDWLRQGHO¶HQYLURQQHPHQWGRLWrWUHIRQGpHVXUXQHpYDOXDWLRQ GHVULVTXHVHWMXVWLILpHGDQVOD&&6 E /HVSULQFLSDOHVFRQVLGpUDWLRQVORUVGHO¶pYDOXDWLRQGHVULVTXHVSRXUOD&&6G¶XQ
 LVRODWHXU GRLYHQW LQFOXUH VDQV WRXWHIRLV V¶\ OLPLWHU OH SURJUDPPH GH ELR
 GpFRQWDPLQDWLRQOHGHJUpG¶DXWRPDWLVDWLRQO¶LPSDFWGHVPDQLSXODWLRQVjWUDYHUV OHVJDQWVVXVFHSWLEOHVGHFRPSURPHWWUHODSURWHFWLRQSDUO¶DLUSULPDLUHGHVSRLQWV FULWLTXHV SRXU OH SURFpGp O¶LPSDFW G¶XQH SHUWH SRWHQWLHOOH GH O¶LQWpJULWp GH OD EDUULqUHHWRXGHVJDQWVOHVPpFDQLVPHVGHWUDQVIHUWXWLOLVpVHWOHVDFWLYLWpVWHOOHV
 TXHOHPRQWDJHRXODPDLQWHQDQFHTXLSHXYHQWQpFHVVLWHUO¶RXYHUWXUHGHVSRUWHV
 DYDQWODELRGpFRQWDPLQDWLRQILQDOHGHO¶LVRODWHXU/RUVTXHG¶DXWUHV ULVTXHVOLpV DXSURFpGpVRQWLGHQWLILpVXQQLYHDXSOXVpOHYpGHODFODVVHGHO¶HQYLURQQHPHQW G¶LQVWDOODWLRQ GRLW rWUH FRQVLGpUp jPRLQV TXH FHOD QH VRLW MXVWLILp GHPDQLqUH DSSURSULpHGDQVOD&&6 F 'HVpWXGHVGHYLVXDOLVDWLRQGHO¶pFRXOHPHQWGHO¶DLUGRLYHQWrWUHHIIHFWXpHVDX
 QLYHDX GH O¶LQWHUIDFH GHV LVRODWHXUV RXYHUWV DILQ GH GpPRQWUHU O¶DEVHQFH
 G¶LQWURGXFWLRQG¶DLU

LL 5$%6

/¶HQYLURQQHPHQWLPPpGLDWGHV5$%6XWLOLVpVSRXUOHSURFpGpDVHSWLTXHGRLWFRUUHVSRQGUH
j OD FODVVH % DX PLQLPXP HW GHV YLVXDOLVDWLRQV GH O¶pFRXOHPHQW GH O¶DLU GRLYHQW rWUH
HIIHFWXpHV SRXU GpPRQWUHU O¶DEVHQFH G¶LQWURGXFWLRQ G¶DLU SHQGDQW OHV LQWHUYHQWLRQV \
FRPSULVORUVGHVRXYHUWXUHVGHVSRUWHVOHFDVpFKpDQW

 /HV PDWpULDX[ XWLOLVpV SRXU OHV V\VWqPHV GH JDQWV j OD IRLV SRXU OHV LVRODWHXUV HW OHV
 5$%6 GRLYHQW SUpVHQWHU XQH UpVLVWDQFH PpFDQLTXH HW FKLPLTXH DSSURSULpHV /D IUpTXHQFHGHUHPSODFHPHQWGHVJDQWVGRLWrWUHGpILQLHGDQVOD&&6 L ,VRODWHXUV

D 3RXU OHV LVRODWHXUV OHV WHVWV G¶pWDQFKpLWp GX V\VWqPH GH JDQWV GRLYHQW rWUH HIIHFWXpVjO¶DLGHG¶XQHPpWKRGRORJLHDGDSWpHDXSURFpGpHWjODFULWLFLWp/HV
 WHVWV GRLYHQW rWUH HIIHFWXpV j GHV LQWHUYDOOHV GpILQLV *pQpUDOHPHQW OHV WHVWV G¶LQWpJULWpGHVJDQWVGRLYHQWrWUHHIIHFWXpVDXPLQLPXPDXGpEXWHWjODILQGH FKDTXH ORW RX FDPSDJQH 'HV WHVWV G¶LQWpJULWp VXSSOpPHQWDLUHV GHV JDQWV SHXYHQWrWUHQpFHVVDLUHVHQIRQFWLRQGHODGXUpHYDOLGpHGHODFDPSDJQH
 /DVXUYHLOODQFHGHO¶LQWpJULWpGHVJDQWVGRLWFRPSUHQGUHXQHLQVSHFWLRQYLVXHOOH
 jFKDTXHXWLOLVDWLRQRXVXLWHjXQHPDQLSXODWLRQVXVFHSWLEOHG¶DIIHFWHUO¶LQWpJULWp GXV\VWqPH
 3RXU OHV SURFHVVXV DVHSWLTXHVPDQXHOV DX FRXUV GHVTXHOV VRQW SURGXLWV XQH
 VHXOHXQLWpRXGHVORWVGHSHWLWHWDLOOHODIUpTXHQFHGHYpULILFDWLRQGHO¶LQWpJULWp SHXWrWUHEDVpH VXU G¶DXWUHV FULWqUHV WHOV TXH OH GpEXW HW OD ILQ GH FKDTXH
 IDEULFDWLRQ
E /HVWHVWVG¶LQWpJULWpG¶pWDQFKpLWpGHVV\VWqPHVG¶LVRODWHXUVGRLYHQWrWUHHIIHFWXpV jLQWHUYDOOHVGpILQLV

LL 5$%6

/HVJDQWVXWLOLVpVGDQVOD]RQHGHFODVVH$GRLYHQWrWUHVWpULOHVDYDQWLQVWDOODWLRQHW VWpULOLVpVRXELRGpFRQWDPLQpVSDUXQHPpWKRGHYDOLGpHDYDQWFKDTXHFDPSDJQH GHIDEULFDWLRQ6LOHVJDQWVVRQWH[SRVpVjO¶HQYLURQQHPHQWLPPpGLDWGX5$%6XQH GpVLQIHFWLRQ j O¶DLGH G¶XQH PpWKRGH DSSURXYpH GRLW rWUH HIIHFWXpH DSUqV FKDTXH H[SRVLWLRQ/HVJDQWVGRLYHQWrWUHH[DPLQpVYLVXHOOHPHQWjFKDTXHXWLOLVDWLRQHWGHV
WHVWVG¶LQWpJULWpGRLYHQWrWUHHIIHFWXpVjLQWHUYDOOHVUpJXOLHUV
 /HVPpWKRGHVGHGpFRQWDPLQDWLRQQHWWR\DJHHWELRGpFRQWDPLQDWLRQHWORUVTXHFHODHVW
 DSSOLFDEOHLQDFWLYDWLRQGHVPDWLqUHVELRORJLTXHVGRLYHQWrWUHGpILQLHVHWPDLWULVpHVGH
 PDQLqUHDSSURSULpH/HSURFHVVXVGHQHWWR\DJHDYDQWO¶pWDSHGHELRGpFRQWDPLQDWLRQHVW
 HVVHQWLHO WRXW UpVLGX UHVWDQW SHXW LQKLEHU O¶HIILFDFLWp GX SURFHVVXV GH ELR GpFRQWDPLQDWLRQ'HVSUHXYHVGRLYHQWpJDOHPHQWrWUHGLVSRQLEOHVSRXUGpPRQWUHUTXHOHV DJHQWVGHQHWWR\DJHHWGHELRGpFRQWDPLQDWLRQXWLOLVpVQ¶RQWSDVG¶HIIHWVXUODTXDOLWpGX SURGXLWIDEULTXpjO¶LQWpULHXUGX5$%6RXGHO¶LVRODWHXU

L 3RXUOHVLVRODWHXUV

/H SURFHVVXV GH ELRGpFRQWDPLQDWLRQ GH O¶LQWpULHXU GRLW rWUH DXWRPDWLVp YDOLGp HW
PDLWULVpVHORQGHVSDUDPqWUHVGHF\FOHELHQGpILQLVHWGRLWLQFOXUHXQDJHQWVSRULFLGH VRXV XQHIRUPH DSSURSULpH SDU H[HPSOH VRXVIRUPH JD]HXVH RX YDSRULVpH /HV JDQWV GRLYHQW rWUH FRUUHFWHPHQW pWHQGXV DYHF OHV GRLJWV VpSDUpV SRXU DVVXUHU OH FRQWDFW DYHF O¶DJHQW /HV PpWKRGHV XWLOLVpHV QHWWR\DJH HW ELRGpFRQWDPLQDWLRQ
GRLYHQWUHQGUHOHVVXUIDFHVLQWpULHXUHVHWOD]RQHFULWLTXHGHO¶LVRODWHXUH[HPSWHVGH
PLFURRUJDQLVPHVYLDEOHV

LL 3RXUOHV5$%6

/DELRGpFRQWDPLQDWLRQGRLWLQFOXUHO¶DSSOLFDWLRQV\VWpPDWLTXHG¶XQDJHQWVSRULFLGHj O¶DLGHG¶XQHPpWKRGHYDOLGpHHWD\DQWGpPRQWUpGHPDQLqUHUREXVWHOHWUDLWHPHQWGH
WRXWHV OHV VXUIDFHV  LQWHUQHV DILQ G¶DVVXUHU XQ HQYLURQQHPHQW DSSURSULp SRXU OH SURFpGpDVHSWLTXH
48$/,),&$7,21'(66$//(635235(6(7'(6(48,3(0(1769(17,/(63$5'(/¶$,5 35235(
 &KDTXHRSpUDWLRQGHIDEULFDWLRQH[LJHXQQLYHDXDSSURSULpGHSURSUHWpGDQVO¶pWDW©HQ
 DFWLYLWpªDILQGHPLQLPLVHUOHULVTXHGHFRQWDPLQDWLRQGXSURGXLWRXGHVpTXLSHPHQWV PDQLSXOpV/HVVDOOHVSURSUHVHWOHVpTXLSHPHQWVYHQWLOpVSDUGHO¶DLUSURSUHWHOVTXHOHV XQLWpV GH IOX[ G¶DLU XQLGLUHFWLRQQHO 8'$) OHV 5$%6 HW OHV LVRODWHXUV XWLOLVpV SRXU OD IDEULFDWLRQGHSURGXLWVVWpULOHVGRLYHQWrWUHTXDOLILpVHQIRQFWLRQGHVFDUDFWpULVWLTXHVGH O¶HQYLURQQHPHQW'HVQLYHDX[GHSURSUHWpDSSURSULpVGRLYHQWrWUHPDLQWHQXVGDQVOHXU pWDW©DXUHSRVªRX©HQDFWLYLWpª
 
 /HVVDOOHVSURSUHVHWOHVpTXLSHPHQWVYHQWLOpVSDUGHO¶DLUSURSUHGRLYHQWrWUHTXDOLILpV
 FRQIRUPpPHQW j ODPpWKRGRORJLH UHTXLVH GDQV O¶DQQH[H  /D TXDOLILFDWLRQ GHV VDOOHV
 SURSUHV \ FRPSULV OHXU FODVVLILFDWLRQ GRLW rWUH FODLUHPHQW GLVWLQFWH GHOD VXUYHLOODQFH RSpUDWLRQQHOOHGHO¶HQYLURQQHPHQW
 /DTXDOLILFDWLRQGHVVDOOHVSURSUHVHWGHVpTXLSHPHQWVYHQWLOpVSDUGHO¶DLUSURSUHHVWOH
 SURFHVVXV JOREDO G¶pYDOXDWLRQ GX QLYHDX GH FRQIRUPLWp G¶XQH VDOOH SURSUH RX G¶XQ
 pTXLSHPHQWYHQWLOpFODVVpVFRQIRUPpPHQWjOHXUXWLOLVDWLRQ&RPPHSUpYXSDUO¶DQQH[H ODTXDOLILFDWLRQGHVVDOOHVSURSUHVHWGHVpTXLSHPHQWVYHQWLOpVSDUGHO¶DLUSURSUHGRLW
 LQFOXUHORUVTXHFHODHVWSHUWLQHQWVHORQODFRQFHSWLRQXWLOLVDWLRQ

L /DUHFKHUFKHGHIXLWHHWOHFRQWU{OHG¶LQWpJULWpGXILOWUHLQVWDOOp LL /HPHVXUDJHGXIOX[G¶DLUGpELWHWYLWHVVH

LLL /HPHVXUDJHGHODSUHVVLRQGLIIpUHQWLHOOHGHO¶DLU

LY /DYLVXDOLVDWLRQGHODGLUHFWLRQGHO¶pFRXOHPHQWGHO¶DLU

Y /HQLYHDXGHFRQWDPLQDWLRQPLFURELHQQHGHO¶DLUHWGHVVXUIDFHV

YL /HPHVXUDJHGHODWHPSpUDWXUH

etc. etc.

What is happening ?????

**Comment by Bearsaerker** [comment]
Always include which command you use. What command did you use? Did you set --ocr_all_pages?

**Comment by VikParuchuri** [comment]
Yes, forcing ocr will fix this - this happens when your pdf has bad ocr text
