### ISSUE TITLE
Improved Table Parsing

### ISSUE THREAD

**Issue by m9e** [VikParuchuri/marker#290]
First, impressive work. I thought I'd provide a vibe on a first run through. And I read the README and understand this is challenging. Source doc: https://investors.exeloncorp.com/static-files/2068bc1d-d1aa-49a8-b49f-d8d01ef43a14

there are a bunch of good examples here of cases both where marker crushes it, and some where it whiffs on tables.

![Screenshot 2024-09-24 at 3 45 24 PM](https://github.com/user-attachments/assets/3a78d09f-a675-40de-9816-ed38e0fc0c74)

is a good view of a particularly challenging table and it gets it *so close*

I also felt this was a particularly good table that is illustrative of that common format where you see horizontal and vertical headers or labels, but then the top left (0,0 if this was a grid counted down and right) is blank. Will join discord!

**Comment by VikParuchuri** [comment]
Table parsing is improved a lot now
