### ISSUE TITLE
fix: cannot close object, library is destroyed. this may cause a memory leak

### ISSUE THREAD

**Issue by mratanusarkar** [VikParuchuri/marker#299]
The library lacks good documentation.

I was trying to use `from marker.convert import convert_single_pdf` from this [reference code line](https://github.com/VikParuchuri/marker/blob/master/convert_single.py#L34), and on run, I faced the following in the stack trace:

```
-> Cannot close object, library is destroyed. This may cause a memory leak!
-> Cannot close object, library is destroyed. This may cause a memory leak!
-> Cannot close object, library is destroyed. This may cause a memory leak!
```

**Comment by VikParuchuri** [comment]
This is a warning related to pypdfium2 - it needs to be the top import.  Happy to take documentation PRs.
