### ISSUE TITLE
Python crashes during table recognition when using MPS

### ISSUE THREAD

**Issue by hyericlee** [VikParuchuri/marker#301]
Performing `marker_single` crashes Python during table recognition step with error:
> /AppleInternal/Library/BuildRoots/4ff29661-3588-11ef-9513-e2437461156c/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraph.mm:871: failed assertion `Placeholder shape mismatches (expected 1 vs got tensorData with 3200) at dimIdx = 0'

Command used:
> EXTRACT_IMAGES=False TORCH_DEVICE=mps marker_single test/test.pdf test --batch_multiplier 4 --langs English

`marker-pdf` version:
> 0.3.0

<img width="758" alt="Screenshot 2024-10-18 at 10 29 46 AM" src="https://github.com/user-attachments/assets/53e83ffb-8ec4-4748-87c5-8de22dc24a8e"> 

<img width="273" alt="Screenshot 2024-10-18 at 10 38 20 AM" src="https://github.com/user-attachments/assets/a0eb6e9d-6e96-4e8b-ac94-6d0556121efb">

**Comment by hyericlee** [comment]
Bonus: Would love to have an `EXTRACT_TABLES=False` setting!

**Comment by Asber777** [comment]
I came across the same problem. and I set`  EXTRACT_TABLES=False` which is not working

**Comment by lovekesh-thakur** [comment]
i am also stuck with same error. 
<img width="1798" alt="Screenshot 2024-10-18 at 12 42 40 PM" src="https://github.com/user-attachments/assets/2d8a4c36-5c59-4712-94b8-94eb16e50cb3">

**Comment by VikParuchuri** [comment]
I can't repro this on an M1 mac.  Can you share some details, please?

- processor type
- os version
- PDF file that you used
- Torch version

MPS is unfortunately quite buggy

**Comment by lovekesh-thakur** [comment]
> I can't repro this on an M1 mac. Can you share some details, please?
> 
> * processor type
> * os version
> * PDF file that you used
> * Torch version
> 
> MPS is unfortunately quite buggy

[iess102.pdf](https://github.com/user-attachments/files/17435268/iess102.pdf)
[requirements.txt](https://github.com/user-attachments/files/17435271/requirements.txt)

OS : Sonoma 14.4.1
Processor : M1 Pro 
Torch : 2.5.0 
command : marker_single ./data/input/ncert/iess102.pdf ./data/output

**Comment by hyericlee** [comment]
[hutchinsons-eyes-sample.pdf](https://github.com/user-attachments/files/17435423/hutchinsons-eyes-sample.pdf)

OS : Sonoma 14.6.1
Processor : M1 Pro 32GB
torch : 2.5.0
torchvision: 0.20.0
command :
> EXTRACT_IMAGES=False TORCH_DEVICE=mps marker_single hutchinsons/hutchinsons-eyes-sample.pdf hutchinsons --batch_multiplier 4 --langs English

**Comment by VikParuchuri** [comment]
Thanks for the repro cases - they're also helping me chase down some unrelated bugs with layout :)

**Comment by VikParuchuri** [comment]
FYI, this seems to not impact torch 2.4.1, only 2.5, so it's likely a bug in pytorch

**Comment by VikParuchuri** [comment]
Ok, fixed, will release shortly.

**Comment by hyericlee** [comment]
Can confirm issue fixed in version `0.3.1`, thank you!! 🎉
