### ISSUE TITLE
maybe a bug in V0.3

### ISSUE THREAD

**Issue by EricYangCn** [VikParuchuri/marker#302]
I installed marker-pdf by:pip install marker-pdf,my program works well in Oct 17,but I was confused by the following information：
  File "/usr/local/bin/marker_single", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/convert_single.py", line 33, in main
    full_text, images, out_meta = convert_single_pdf(fname, model_lst, max_pages=args.max_pages, langs=langs, batch_multiplier=args.batch_multiplier, start_page=args.start_page)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/marker/convert.py", line 150, in convert_single_pdf
    infer_heading_levels(pages)
  File "/usr/local/lib/python3.11/dist-packages/marker/cleaners/headings.py", line 118, in infer_heading_levels
    avg_height = sum(block_heights) / len(block_heights)
                 ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero

After checked source code in github, I found a new version had been released, so I install marker-pdf v0.2.17 to replace the latest version,  my code do their job very well.

**Comment by VikParuchuri** [comment]
Will fix in next release
