### ISSUE TITLE
ReadTimeout: (ReadTimeoutError

### ISSUE THREAD

**Issue by ssfd7** [VikParuchuri/marker#308]
Hello I am getting this error:

- ReadTimeout: (ReadTimeoutError("HTTPSConnectionPool(host='cdn-lfs-us-1.hf.co', port=443): Read timed out.

for this code below:
```
from marker.convert import convert_single_pdf
from marker.models import load_all_models

fpath = "my.pdf"
model_lst = load_all_models()
full_text, images, out_meta = convert_single_pdf(fpath, model_lst)
```
Any idea?

**Comment by VikParuchuri** [comment]
Looks like your machine can't connect to the huggingface hub to download the models.  Possibly firewall related.
