### ISSUE TITLE
Header level not set correctly

### ISSUE THREAD

**Issue by barbem** [VikParuchuri/marker#310]
Hi there,
First of all, thank you for this tool! I am a blind user, I use a lot of markdown format and PDFs are often not accessible.

In your example from Think Python, the chapters are set to level 1 and all other headings are set to level 2:

```
# Chapter 1
...
## 1.3 What is debugging?
...
## 1.3.1 Syntax errors
`

Section 1.3.1 should be level 3.
It should be easy to use the section number to determine the level of the header.
Thank you.

**Comment by Shubhamkumar782** [comment]
Hi @VikParuchuri 

If you see the same pdf example Think Python. 
Markdown tags are not static for one level.
For example Chapter 1  and chapter 5 are having different tag actually Chapter 5 is not getting identified as Heading this happened with multiple chapter.
Is there a way to fix this ?

**Comment by barbem** [comment]
I used the example of your ReadMe to demonstrate the problem.  I have the same issue for every documents that I convert with Marker.

**Comment by barbem** [comment]
I am not able to reopen this issue.
