### ISSUE TITLE
KeyError: 'sdpa'

### ISSUE THREAD

**Issue by miloskovacevic68** [VikParuchuri/marker#318]
I installed the newest version of marker-pdf with pip install marker-pdf in a newly created venv environment with python 3.10.
When i try to use marker_single from cli i get the error:

Loaded detection model vikp/surya_det3 on device cuda with dtype torch.float16
Loaded detection model vikp/surya_layout3 on device cuda with dtype torch.float16
Traceback (most recent call last):
  File "/home/milos/PycharmProjects/raga_marker/venv/bin/marker_single", line 8, in <module>
    sys.exit(main())
  File "/home/milos/PycharmProjects/raga_marker/venv/lib/python3.10/site-packages/convert_single.py", line 31, in main
    model_lst = load_all_models()
  File "/home/milos/PycharmProjects/raga_marker/venv/lib/python3.10/site-packages/marker/models.py", line 78, in load_all_models
    order = setup_order_model(device, dtype)
  File "/home/milos/PycharmProjects/raga_marker/venv/lib/python3.10/site-packages/marker/models.py", line 66, in setup_order_model
    model = load_order_model()
  File "/home/milos/PycharmProjects/raga_marker/venv/lib/python3.10/site-packages/surya/model/ordering/model.py", line 27, in load_model
    model = OrderVisionEncoderDecoderModel.from_pretrained(checkpoint, config=config, torch_dtype=dtype)
  File "/home/milos/PycharmProjects/raga_marker/venv/lib/python3.10/site-packages/transformers/models/vision_encoder_decoder/modeling_vision_encoder_decoder.py", line 376, in from_pretrained
    return super().from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/home/milos/PycharmProjects/raga_marker/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4096, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/milos/PycharmProjects/raga_marker/venv/lib/python3.10/site-packages/transformers/models/vision_encoder_decoder/modeling_vision_encoder_decoder.py", line 199, in __init__
    decoder = AutoModelForCausalLM.from_config(config.decoder)
  File "/home/milos/PycharmProjects/raga_marker/venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 440, in from_config
    return model_class._from_config(config, **kwargs)
  File "/home/milos/PycharmProjects/raga_marker/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1543, in _from_config
    model = cls(config, **kwargs)
  File "/home/milos/PycharmProjects/raga_marker/venv/lib/python3.10/site-packages/surya/model/ordering/decoder.py", line 495, in __init__
    self.model = MBartOrderDecoderWrapper(config)
  File "/home/milos/PycharmProjects/raga_marker/venv/lib/python3.10/site-packages/surya/model/ordering/decoder.py", line 480, in __init__
    self.decoder = MBartOrderDecoder(config)
  File "/home/milos/PycharmProjects/raga_marker/venv/lib/python3.10/site-packages/surya/model/ordering/decoder.py", line 294, in __init__
    self.layers = nn.ModuleList([MBartOrderDecoderLayer(config) for _ in range(config.decoder_layers)])
  File "/home/milos/PycharmProjects/raga_marker/venv/lib/python3.10/site-packages/surya/model/ordering/decoder.py", line 294, in <listcomp>
    self.layers = nn.ModuleList([MBartOrderDecoderLayer(config) for _ in range(config.decoder_layers)])
  File "/home/milos/PycharmProjects/raga_marker/venv/lib/python3.10/site-packages/surya/model/ordering/decoder.py", line 209, in __init__
    self.self_attn = MBART_ATTENTION_CLASSES[config._attn_implementation](
KeyError: 'sdpa'

Please help!

**Comment by AdrianY0809** [comment]
The same problem

**Comment by xunmenglt** [comment]
I solve it by 'pip install transformers==4.45.2'

**Comment by MarcinRutecki** [comment]
@xunmenglt thank you. It worked

**Comment by johmicrot** [comment]
I also confirm @xunmenglt solved the issue for me.

**Comment by VikParuchuri** [comment]
Yes, this is a bug with transformers 4.46.  Will patch today

**Comment by Jensssen** [comment]
This is what I call realtime-bug-fixing. Amazing! 🥇

**Comment by VikParuchuri** [comment]
See https://github.com/VikParuchuri/marker/pull/319, will merge shortly

**Comment by miloskovacevic68** [comment]
Thank you. It works well!

**Comment by WaleedChughtai30** [comment]
> I solve it by 'pip install transformers==4.45.2'

worked for me too!

**Comment by HeJLDLUT** [comment]
amazing


> 我通过 'pip install transformers==4.45.2' 来解决它

amazing

**Comment by gramster** [comment]
Hit this today from a fresh repo clone, so while the workaround works it doesn't seem to be fixed in this repo itself.

**Comment by HRV1527** [comment]
I am working with marker-pdf 1.6.2 in a venv created using Python 3.12.3. When I am trying to use marker I am facing the following error:

Cell In[7], line 355, in TreeParser.populate_tree(self, tree)
    353 file = tree.file
    354 filename = self.get_filename(file)
--> 355 self.generate_markdown(file, filename)
    356 self.generate_toc(file, filename)
    358 recentNodeDict = {}

Cell In[7], line 17, in TreeParser.generate_markdown(self, file, filename)
     11 if not output_exists(os.path.join(OUTPUT_DIR, filename), filename):
     12     config = {
     13         "output_format": "markdown",
     14         "use_llm": False,
     15     }
     16     converter = PdfConverter(
---> 17         artifact_dict=create_model_dict(),
     18         config=config
     19     )
     20     rendered = converter(file)
     21     os.mkdir(os.path.join(OUTPUT_DIR, filename))

File ~/Desktop/Scrappers/NeuScraper/myenv/lib/python3.12/site-packages/marker/models.py:16, in create_model_dict(device, dtype)
     12 def create_model_dict(device=None, dtype=None) -> dict:
     13     return {
     14         "layout_model": LayoutPredictor(device=device, dtype=dtype),
     15         "texify_model": TexifyPredictor(device=device, dtype=dtype),
---> 16         "recognition_model": RecognitionPredictor(device=device, dtype=dtype),
     17         "table_rec_model": TableRecPredictor(device=device, dtype=dtype),
     18         "detection_model": DetectionPredictor(device=device, dtype=dtype),
     19         "inline_detection_model": InlineDetectionPredictor(device=device, dtype=dtype),
     20         "ocr_error_model": OCRErrorPredictor(device=device, dtype=dtype)
     21     }


File ~/Desktop/Scrappers/NeuScraper/myenv/lib/python3.12/site-packages/surya/common/predictor.py:24, in BasePredictor.__init__(self, checkpoint, device, dtype)
     21 self.processor = None
     22 loader = self.model_loader_cls(checkpoint)
---> 24 self.model = loader.model(device, dtype)
     25 self.processor = loader.processor()

File ~/Desktop/Scrappers/NeuScraper/myenv/lib/python3.12/site-packages/surya/recognition/loader.py:35, in RecognitionModelLoader.model(self, device, dtype)
     32 if dtype is None:
     33     dtype = settings.MODEL_DTYPE
---> 35 config = SuryaOCRConfig.from_pretrained(self.checkpoint)
     36 decoder_config = config.decoder
     37 decoder = SuryaOCRDecoderConfig(**decoder_config)

File ~/Desktop/Scrappers/NeuScraper/myenv/lib/python3.12/site-packages/surya/common/s3.py:132, in S3DownloaderMixin.from_pretrained(cls, pretrained_model_name_or_path, *args, **kwargs)
    129             print(f"Failed to download {pretrained_model_name_or_path} after {retries} attempts.")
    130             raise e  # Reraise exception after max retries
--> 132 return super().from_pretrained(local_path, *args, **kwargs)

File ~/Desktop/Scrappers/NeuScraper/myenv/lib/python3.12/site-packages/transformers/configuration_utils.py:569, in PretrainedConfig.from_pretrained(cls, pretrained_model_name_or_path, cache_dir, force_download, local_files_only, token, revision, **kwargs)
    563     if config_dict["model_type"] != cls.model_type:
    564         logger.warning(
    565             f"You are using a model of type {config_dict['model_type']} to instantiate a model of type "
    566             f"{cls.model_type}. This is not supported for all configurations of models and can yield errors."
    567         )
--> 569 return cls.from_dict(config_dict, **kwargs)

File ~/Desktop/Scrappers/NeuScraper/myenv/lib/python3.12/site-packages/transformers/configuration_utils.py:766, in PretrainedConfig.from_dict(cls, config_dict, **kwargs)
    763 for key in to_remove:
    764     kwargs.pop(key, None)
--> 766 logger.info(f"Model config {config}")
    767 if return_unused_kwargs:
    768     return config, kwargs

File ~/Desktop/Scrappers/NeuScraper/myenv/lib/python3.12/site-packages/transformers/configuration_utils.py:798, in PretrainedConfig.__repr__(self)
    797 def __repr__(self):
--> 798     return f"{self.__class__.__name__} {self.to_json_string()}"

File ~/Desktop/Scrappers/NeuScraper/myenv/lib/python3.12/site-packages/transformers/configuration_utils.py:909, in PretrainedConfig.to_json_string(self, use_diff)
    897 """
    898 Serializes this instance to a JSON string.
    899 
   (...)    906     `str`: String containing all the attributes that make up this configuration instance in JSON format.
    907 """
    908 if use_diff is True:
--> 909     config_dict = self.to_diff_dict()
    910 else:
    911     config_dict = self.to_dict()

File ~/Desktop/Scrappers/NeuScraper/myenv/lib/python3.12/site-packages/transformers/configuration_utils.py:818, in PretrainedConfig.to_diff_dict(self)
    815 default_config_dict = PretrainedConfig().to_dict()
    817 # get class specific config dict
--> 818 class_config_dict = self.__class__().to_dict() if not self.has_no_defaults_at_init else {}
    820 serializable_config_dict = {}
    822 # Only serialize values that differ from the default config,
    823 # except always keep the 'config' attribute.

File ~/Desktop/Scrappers/NeuScraper/myenv/lib/python3.12/site-packages/surya/recognition/model/config.py:17, in SuryaOCRConfig.__init__(self, **kwargs)
     14 def __init__(self, **kwargs):
     15     super().__init__(**kwargs)
---> 17     encoder_config = kwargs.pop("encoder")
     18     decoder_config = kwargs.pop("decoder")
     20     self.encoder = encoder_config

KeyError: 'encoder'

please help !!!
