### ISSUE TITLE
Zero height box found, cannot convert properly

### ISSUE THREAD

**Issue by theesfeld** [VikParuchuri/marker#33]
Every single PDF I have tried gets the following error:

```
Zero height box found, cannot convert properly
```

```
Traceback (most recent call last):
  File "/Users/grim/src/marker/convert_single.py", line 22, in <module>
    full_text, out_meta = convert_single_pdf(fname, model_lst, max_pages=args.max_pages, parallel_factor=args.parallel_factor)
  File "/Users/grim/src/marker/marker/convert.py", line 108, in convert_single_pdf
    block_types = detect_document_block_types(
  File "/Users/grim/src/marker/marker/segmentation.py", line 51, in detect_document_block_types
    encodings, metadata, sample_lengths = get_features(doc, blocks)
  File "/Users/grim/src/marker/marker/segmentation.py", line 160, in get_features
    encoding, other_data = get_page_encoding(doc[i], blocks[i])
  File "/Users/grim/src/marker/marker/segmentation.py", line 104, in get_page_encoding
    raise ValueError
ValueError
```

macOS 14.2
python 3.9

installed via exact instructions from git repo

**Comment by VikParuchuri** [comment]
That's strange, that will only happen when detected bboxes are 0 or less height (something weird with the pdf).  Can you share the pdfs you're trying?

**Comment by Blacktothefuture** [comment]
@VikParuchuri 
Happening with select pdfs for me as well
[design-for-the-real-world-victor-papanek.pdf](https://github.com/VikParuchuri/marker/files/13592924/design-for-the-real-world-victor-papanek.pdf)

**Comment by theesfeld** [comment]
good find!!

**Comment by theesfeld** [comment]
can I privately send you a pdf I am having issues with?

**Comment by VikParuchuri** [comment]
If anyone has bandwidth to test the fix currently on the `dev` branch [here](https://github.com/VikParuchuri/marker/pull/37), I'd appreciate it!

**Comment by VikParuchuri** [comment]
I've merged the PR, so am closing this.  Please re-open if you notice any issues.

**Comment by balabis** [comment]
Hey @VikParuchuri 
Wanted to report on the rotation issue - I'm running `marker` on Google Colab with `!marker_single /content/test3.pdf /content--batch_multiplier 4` and if `test3.pdf` is rotated 90 degrees I get nonsensical markdown. When i rotate the document back with `Preview` on my mac and upload the file again to Google Colab, the markdown returned is perfect.
