### ISSUE TITLE
does marker support multiple languages

### ISSUE THREAD

**Issue by miloskovacevic68** [VikParuchuri/marker#330]
Hello,
i use marker to extract texts from multiple languages. I also use surya as an OCR engine (I suppose it is markers default option since i have a gpu).

How can i set two or three languages if this is possible.
How to set it from python code.

Regards, Milos

**Comment by VikParuchuri** [comment]
Marker works with all languages - you don't need to specify languages by default, in fact things work slightly better if you don't.  The only reason to specify them is if you notice issues.  In that case, you can specify up to 4.

**Comment by miloskovacevic68** [comment]
Thanks.
I noticed some problems with Cyrillic text (Serbian language) so I would
like to try to specify Serbian Cyrillic besides English. How can i do that
from python api? Do i need to change something in library files or i can
do that dynamically?

Thank you for your kind support,
Milos

**Comment by svenha** [comment]
@miloskovacevic68 If calling `marker_single`, you can try the option `--languages="sr,en"` .
