### ISSUE TITLE
Why the model not as good as Nougat?

### ISSUE THREAD

**Issue by liJay010** [VikParuchuri/marker#36]
Why is the conversion result not as good as Nougat, especially when it comes to handling formulas and tables? Marker conversion introduces many errors, while Nougat has almost no errors.

**Comment by VikParuchuri** [comment]
Nougat passes the whole pdf image through an LLM, whereas marker only passes parts and uses the text in the PDF for the rest.

This means that marker is faster, and more accurate in most cases.  However, nougat is more accurate on pdfs similar to its training data (arxiv scientific papers).

Nougat is a great model, and I'd recommend using it if it's better for your use case!  PDF is a tricky format, so different models will work better on different kinds of docs.
