### ISSUE TITLE
Poor parsing

### ISSUE THREAD

**Issue by nunamia** [VikParuchuri/marker#4]
[1.pdf](https://github.com/VikParuchuri/marker/files/13522916/1.pdf)
[1.md](https://github.com/VikParuchuri/marker/files/13522917/1.md)

Did I use it wrong?

**Comment by VikParuchuri** [comment]
Thanks for the example.  It looks like the equations aren't recognized properly.  I'll test this more and see if I can fix.

**Comment by krainboltgreene** [comment]
@VikParuchuri Do you want more examples of parsing "difficulties"?

**Comment by VikParuchuri** [comment]
Sure, those will help me improve it.

**Comment by fblissjr** [comment]
@VikParuchuri I've been working on doc ai related things for years - this is one of the most elegant libraries I've seen, and using techniques/models that I've found worked best (in isolation). Great work here - parsing is great, tables are way better than I've seen from other attempts, including my own. Nice work.
