### ISSUE TITLE
Takes too much time on M1 Apple Silicon chip

### ISSUE THREAD

**Issue by RadientBrain** [VikParuchuri/marker#40]
I am trying to test just a small pdf of 8 pages with normal text on m1 silicon chip with CPU with `--parallel_factor 1000` and it takes around 1 minute. And the documentation in README claims quite less time per page. Can you please explain why is this and that did you use GPUs for benchmarking for speed and if yes then what was the configuration so I can achieve this.

**Comment by VikParuchuri** [comment]
Set parallel factor to max 2.  Set `TORCH_DEVICE` setting to `mps`.  See how to adjust settings in the README.

**Comment by RadientBrain** [comment]
@VikParuchuri still no luck, now it gives error:

NotImplementedError: The operator \'aten::roll\' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.\n'

**Comment by VikParuchuri** [comment]
Torch mps support for the roll op was added in Feb.  You must have an old torch version.  Make sure you followed the install instructions.  Please don't open multiple issues.

**Comment by RadientBrain** [comment]
well I upgraded the torch version, the error is gone, but still it takes significant amount of time

**Comment by RadientBrain** [comment]
I am just wanting to have a faster thing that you claim to have achieved, when I test this with mps on an 8 page pdf, it takes around 1 minute which is same as the cpu version. So maybe can you please tell the configuration that you tried at your end to get the speed as given in readme? like the gpus or something like that? That would be of very help!

**Comment by VikParuchuri** [comment]
Things that will impact speed:

- How many pages need OCR (as mentioned in the README, marker is optimized for docs that mostly don't need OCR, if every page has to be OCRed, it will slow down).  If every page needs OCR, you can set `OCR_PARALLEL_WORKERS` higher to speed things up.
- Correct setup/configuration, including of torch
- Various settings like batch sizes, etc.

All benchmarks were done on an A6000 GPU, but I can convert 100 page pdfs in 80 seconds using an M1.  Try running the benchmark if you want a way to compare performance reliably.
