### ISSUE TITLE
PdfiumError: Failed to load document (PDFium: File access error).

### ISSUE THREAD

**Issue by KikeVen** [VikParuchuri/marker#401]
Windows 11
venv 3.10
32 GB RAM

```bash
(venv) PS ...> marker_gui

File "D:\Users\k\Documents\03_work\0_python\1_sandbox\marker-pdf\venv\lib\site-packages\pypdfium2\_helpers\document.py", line 678, in _open_pdf
    raise PdfiumError(f"Failed to load document (PDFium: {pdfium_i.ErrorToStr.get(err_code)}).")

 (venv) PS ...> marker_single PRODUCT_ROADMAP.pdf

lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ub97c' in position 2662: character maps to <undefined>
```

This application is far from ready. Thank you

**Comment by VikParuchuri** [comment]
Your system encoding is not utf-8.  You can set `PYTHONIOENCODING=utf8`.  I'll force utf-8 encoding in a future update

**Comment by Xgz20** [comment]
hi, set the environment variables, but after importing the pdf is still reported this error, can help explain the reason, thank you very much!
![marker-error](https://github.com/user-attachments/assets/8b66887f-d096-4179-97ae-c75fceb9d980)
![PixPin_2024-12-04_16-55-26](https://github.com/user-attachments/assets/6b545c27-1b2c-4952-b060-d85f90d26e7d)



> Your system encoding is not utf-8. You can set `PYTHONIOENCODING=utf8`. I'll force utf-8 encoding in a future update

**Comment by VikParuchuri** [comment]
This is actually a different error - looks like the file can't be accessed - are permissions correct?  If you can share the PDF, I can take a look.

**Comment by andrebagoes** [comment]
![image](https://github.com/user-attachments/assets/942d36ca-2a09-4c1b-9f92-9487eab525ac)
its working on single one, but if using folder i have the same problem as [Xgz20](https://github.com/Xgz20)

and also im on the same envireontment win 10 wiht 3.11

**Comment by andrebagoes** [comment]
> This is actually a different error - looks like the file can't be accessed - are permissions correct? If you can share the PDF, I can take a look.

its a path issue i supoose, because when i hit it with single one, it hit file directly, but when its folder, its having the trouble, any idea ?
