### ISSUE TITLE
Missing requirements.txt in repository, and indexer error on execution

### ISSUE THREAD

**Issue by nekiee13** [VikParuchuri/marker#41]
No requirements.txt file on the VikParuchuri repo
	https://github.com/VikParuchuri/marker

Used fork with requirements.txt to see missing packages
	https://github.com/gardner/marker

Followed instructions for Windows
	https://github.com/VikParuchuri/marker/issues/12

Detectron 2 installation without issues (ref. Fix the "identifier 'single_box_iou_rotated' is undefined")

Adjusted requiremenst.txt - removed detectron2 (already installed), changed nougat to nougat-ocr.

Installed Pillow 10.0.1 (had to differ from required Pillow==9.5.0, because of other dependencies, see bellow)

(D:\03Marker\vMarker) D:\03Marker\vMarker>pip show Pillow
	Name: Pillow
	Version: 10.0.1
	Summary: Python Imaging Library (Fork)
	Home-page: https://python-pillow.org
	Author: Jeffrey A. Clark (Alex)
	Author-email: aclark@aclark.net
	License: HPND
	Location: d:\03marker\vmarker\lib\site-packages
	Requires:
	Required-by: detectron2, fvcore, imageio, img2pdf, layoutparser, matplotlib, ocrmypdf, pdf2image, 	pdfplumber, pikepdf, pytesseract, reportlab, scikit-image, torchvision

(D:\03Marker\vMarker) D:\03Marker\vMarker>pip check
	No broken requirements found.

(D:\03Marker\vMarker) D:\03Marker\vMarker>python --version
	Python 3.10.13

(D:\00Torch\vTorch) D:\00Torch\vTorch>python
	import torch
	print(torch.__version__)
	print(torch.cuda.is_available())
	2.1.1
	import detectron2
	print(detectron2.__version__)
	0.6
Arranged setting (as best as I could - cuda etc.), according to instructions

When trying to run:

from dir where (convert_single.py is) - D:\03Marker\vMarker\marker
python convert_single.py D:/xLLMDocBase/10CFR50_Appendix_B.pdf  D:/xLLMDocBase/output.md --parallel_factor 2 --max_pages 10

Error:
(D:\03Marker\vMarker) D:\03Marker\vMarker\marker>python convert_single.py D:/xLLMDocBase/10CFR50_Appendix_B.pdf  D:/xLLMDocBase/output.md --parallel_factor 2 --max_pages 10
Traceback (most recent call last):
  File "D:\03Marker\vMarker\marker\convert_single.py", line 3, in <module>
    from marker.convert import convert_single_pdf
  File "D:\03Marker\vMarker\marker\marker\convert.py", line 5, in <module>
    from marker.extract_text import get_text_blocks
  File "D:\03Marker\vMarker\marker\marker\extract_text.py", line 4, in <module>
    from spellchecker import SpellChecker
  File "D:\03Marker\vMarker\lib\site-packages\spellchecker\__init__.py", line 2, in <module>
    from  spellchecker.core import Spellchecker,getInstance
  File "D:\03Marker\vMarker\lib\site-packages\spellchecker\core.py", line 26, in <module>
    from indexer import DictionaryIndex
ModuleNotFoundError: No module named 'indexer'

Can't install indexer (require much earlier python version - 2.7)

Please, can you give me any advice on this? 
Can you send me original requirements.txt?
Is my python command line call correct?

**Comment by VikParuchuri** [comment]
Please see the README.  The installation does not use requirements.txt .  It uses poetry.  Everything is documented in the README.
