### ISSUE TITLE
MPS version not working

### ISSUE THREAD

**Issue by RadientBrain** [VikParuchuri/marker#42]
Set parallel factor to max 2.  Set `TORCH_DEVICE` setting to `mps`.  See how to adjust settings in the README.

_Originally posted by @VikParuchuri in https://github.com/VikParuchuri/marker/issues/40#issuecomment-1850308888_
            
          
This still doesn't work and gives the following error:
            
            NotImplementedError: The operator \'aten::roll\' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.\n'

**Comment by VikParuchuri** [comment]
You must have an old torch version, this op was added in Feb.  You need to follow the instructions for installation.

**Comment by RadientBrain** [comment]
well I upgraded the torch version, the error is gone, but still it takes significant amount of time
