### ISSUE TITLE
 `marker_single` fails with `NoSuchFileError` when loading `dt.onnx` (File Not Found in `site-packages/models/`)

### ISSUE THREAD

**Issue by Liu8Can** [VikParuchuri/marker#423]
**描述:**

When running `marker_single` to convert a PDF file, the process fails with a `NoSuchFileError` indicating that the `dt.onnx` model file cannot be found. The error occurs after the "Recognizing equations" step. The specific error message suggests that `onnxruntime` is trying to load the model from `D:\Program Files\Python3106\lib\site-packages\models\dt.onnx`, but this directory does not exist, and the `dt.onnx` file is not present in the expected location.

**重现步骤:**

1. Install `marker-pdf`: `pip install marker-pdf`
2. Run `marker_single` with a PDF file: `marker_single 25王江涛预测20篇英语一.pdf --output_dir D:\Download\Documents`
3. The process will fail with the following error message.

**预期结果:**

`marker_single` should successfully convert the PDF file to Markdown format without any errors.

**实际结果:**

The conversion process fails with the following error:

```
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from D:\Program Files\Python3106\lib\site-packages\models\dt.onnx failed:Load model D:\Program Files\Python3106\lib\site-packages\models\dt.onnx failed. File doesn't exist
```

**环境:**

*   Operating System:  (Windows 11 Pro, version 24H2, 64-bit)
*   Python Version: 3.10.6

**已尝试的解决方法:**

*   Verified that the directory `D:\Program Files\Python3106\lib\site-packages\models\` does not exist.
*   Searched for the `dt.onnx` file in the Python installation directory and its subdirectories, but the file was not found.
*   Reinstalled `marker-pdf`: `pip uninstall marker-pdf` and then `pip install marker-pdf`.
*   Reinstalled `onnxruntime`: `pip uninstall onnxruntime` and then `pip install onnxruntime`.
*   Searched for the model file in the whole disk, but didn't find `dt.onnx`.
*   Tried `marker_gui`, encountered the same error related to file access.
*   Checked the environment variable, find nothing related.

**其他信息:**

*   The `marker_single` command works fine until the "Recognizing equations" step.
*   The issue seems to be related to the `dt.onnx` model file not being installed correctly or being referenced with an incorrect path.
*   The user confirmed that there are no folders named `models` in the `site-packages` directory.

**请求:**

Could you please investigate this issue and provide guidance on how to resolve it? It seems that the `dt.onnx` model file is either missing from the installation or being referenced with an incorrect path.

**Comment by Liu8Can** [comment]
D:\Download\Documents>marker_single 25王江涛预测20篇英语一.pdf --output_dir D:\Download\Documents
Loaded layout model datalab-to/surya_layout0 on device cpu with dtype torch.float32
Loaded texify model to cpu with torch.float32 dtype
Loaded recognition model vikp/surya_rec2 on device cpu with dtype torch.float32
Loaded table recognition model vikp/surya_tablerec on device cpu with dtype torch.float32
Loaded detection model vikp/surya_det3 on device cpu with dtype torch.float32
Recognizing layout: 100%|██████████████████████████████████████████████████████████████| 25/25 [03:41<00:00,  8.86s/it]
Detecting bboxes: 100%|████████████████████████████████████████████████████████████████| 37/37 [03:42<00:00,  6.02s/it]
Recognizing Text: 100%|████████████████████████████████████████████████████████████| 142/142 [1:12:33<00:00, 30.66s/it]
Recognizing equations: 100%|█████████████████████████████████████████████████████████████| 1/1 [00:10<00:00, 10.04s/it]
Traceback (most recent call last):
  File "D:\Program Files\Python3106\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\Python3106\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python3106\Scripts\marker_single.exe\__main__.py", line 7, in <module>
  File "D:\Program Files\Python3106\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\Program Files\Python3106\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\Program Files\Python3106\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Program Files\Python3106\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\Program Files\Python3106\lib\site-packages\convert_single.py", line 33, in main
    rendered = converter(fpath)
  File "D:\Program Files\Python3106\lib\site-packages\marker\converters\pdf.py", line 109, in __call__
    processor(document)
  File "D:\Program Files\Python3106\lib\site-packages\marker\processors\table.py", line 68, in __call__
    text_lines = get_page_text_lines(
  File "D:\Program Files\Python3106\lib\site-packages\surya\input\pdflines.py", line 12, in get_page_text_lines
    pages_text = dictionary_output(filepath, sort=False, page_range=page_idxs, keep_chars=True, flatten_pdf=flatten_pdf)
  File "D:\Program Files\Python3106\lib\site-packages\pdftext\extraction.py", line 98, in dictionary_output
    block["bbox"] = block["bbox"].bbox
  File "D:\Program Files\Python3106\lib\site-packages\pdftext\extraction.py", line 56, in _get_pages

  File "D:\Program Files\Python3106\lib\site-packages\pdftext\model.py", line 6, in get_model
  File "D:\Program Files\Python3106\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 465, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "D:\Program Files\Python3106\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 526, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from D:\Program Files\Python3106\lib\site-packages\models\dt.onnx failed:Load model D:\Program Files\Python3106\lib\site-packages\models\dt.onnx failed. File doesn't exist
-> Cannot close object, library is destroyed. This may cause a memory leak!

**Comment by iammosespaulr** [comment]
Hi @Liu8Can, can you check the versions of `marker-pdf`, `pdftext` on your machine? (`pip show marker-pdf`, `pip show pdftext`). The latest version of `pdftext` does not need an onnx model to process PDFs. 

You should ideally be seeing
```
$ pip show marker-pdf
Name: marker-pdf
Version: 1.1.0
...
$ pip show pdftext
Name: pdftext
Version: 0.4.0
...
```

**Comment by Liu8Can** [comment]
> Hi @Liu8Can, can you check the versions of `marker-pdf`, `pdftext` on your machine? (`pip show marker-pdf`, `pip show pdftext`). The latest version of `pdftext` does not need an onnx model to process PDFs.
> 
> You should ideally be seeing
> 
> ```
> $ pip show marker-pdf
> Name: marker-pdf
> Version: 1.1.0
> ...
> $ pip show pdftext
> Name: pdftext
> Version: 0.4.0
> ...
> ```

Thanks. I will check it. All are latest versions
C:\Users\DanielSong>pip show pdftext
Name: pdftext
Version: 0.4.0
Summary: Extract structured text from pdfs quickly
Home-page: https://github.com/VikParuchuri/pdftext
Author: Vik Paruchuri
Author-email: vik.paruchuri@gmail.com
License: Apache-2.0
Location: d:\program files\python3106\lib\site-packages
Requires: pydantic, pydantic-settings, pypdfium2
Required-by: marker-pdf, surya-ocr

C:\Users\DanielSong>pip show marker-pdf
Name: marker-pdf
Version: 1.1.0
Summary: Convert PDF to markdown with high speed and accuracy.
Home-page: https://github.com/VikParuchuri/marker
Author: Vik Paruchuri
Author-email: github@vikas.sh
License: GPL-3.0-or-later
Location: d:\program files\python3106\lib\site-packages
Requires: click, ftfy, markdownify, pdftext, Pillow, pydantic, pydantic-settings, python-dotenv, rapidfuzz, regex, surya-ocr, tabled-pdf, tabulate, texify, torch, tqdm, transformers
Required-by:

C:\Users\DanielSong>
