### ISSUE TITLE
Hows the result on Chinese documents?

### ISSUE THREAD

**Issue by lucasjinreal** [VikParuchuri/marker#43]
Hows the result on Chinese documents?

**Comment by lvzenglei** [comment]
> ![Screenshot_2023-12-13-20-03-00-94_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/VikParuchuri/marker/assets/60955803/c001c301-dd1b-4d47-b47d-3769313ee1de)
> 
> 

not Chinese

**Comment by VikParuchuri** [comment]
I have heard from users that Chinese is working well, so I have added preliminary Chinese support in this PR - https://github.com/VikParuchuri/marker/pull/44 .  You just need to set the language to `Chinese`.
