### ISSUE TITLE
How to use it on windows?

### ISSUE THREAD

**Issue by lucasjinreal** [VikParuchuri/marker#45]
How to use it on windows? the dependencies some of them seems not supports windows well.

**Comment by VikParuchuri** [comment]
It should work on windows, but I don't have install instructions for the system packages.  The python packages should all install properly, from what I've heard.

If anyone wants to document the setup instructions for Windows, that would be amazing.

**Comment by nekiee13** [comment]
You can check and try this link:
https://github.com/VikParuchuri/marker/issues/12

It did not work form me, but you can try. In the end I used wsl to install it under Win11.

**Comment by scillidan** [comment]
I used `python39` and Windows10.

Install requirements:

```sh
scoop install python39
pip install poetry
scoop install ghostscript tesseract
```

Get the `tessdata_best`:

```sh
git clone https://github.com/tesseract-ocr/tessdata_best
```

```sh
https://github.com/VikParuchuri/marker
cd marker
python39 -m venv venv
venv\Scripts\activate.bat
poetry install
```

I used GPU, so:

```sh
pip uninstall torch
```

Install CUDA and [the corresponding version of torch](https://pytorch.org/get-started/locally/). I used `CUDA 1.11.8`. Other version should also be able to try.

Create the `local.env`:

```
TORCH_DEVICE=cuda
TESSDATA_PREFIX=WhereIs\tessdata_best
```

Then:

```sh
python convert_single.py in.pdf out.md
```

It tell me to [Enable your device for development](https://learn.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development).

Finally, it said something else, but work well:

```sh
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
D:\binr\pdf_marker\venv\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3527.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
```

**Comment by VikParuchuri** [comment]
The new version (which will be merged shortly into master) will just be a pip package, with no required system dependencies.  So it will work on windows.

**Comment by nekiee13** [comment]
Great.

**Comment by lucasjinreal** [comment]
Does it support markdown format ?
