### ISSUE TITLE
the table issue 

### ISSUE THREAD

**Issue by ouzc12358** [VikParuchuri/marker#47]
seems the table always not be recognized successfully , even it works the format is still not right and cannot be read ,i only use CPU and transfer single file only, which part of the code working on the table function? thanks

**Comment by VikParuchuri** [comment]
Tables are not always recognized 100% properly.  Table recognition happens in `segmentation.py`, and reformatting happens in `cleaners/table.py`.

**Comment by Calvinnncy97** [comment]
I think tables should also be passed to nougat. It does a better job at that.

**Comment by VikParuchuri** [comment]
This should be fixed in the dev branch.  Need to test before merging to master.

**Comment by VikParuchuri** [comment]
Should be fixed in https://github.com/VikParuchuri/marker/pull/116
