### ISSUE TITLE
Windows Installation?

### ISSUE THREAD

**Issue by adityamiskin** [VikParuchuri/marker#5]
Is there a way to use this in windows? It would be really helpful.

**Comment by VikParuchuri** [comment]
I don't have a Windows machine, so I haven't tried it.  If you're willing to try installing it, would love to include the steps in the repo.

**Comment by nekiee13** [comment]
I'm willing to try to install it on Win11 OS, as it is. 
Just few questions:
- can I use Detectron2@v0.6? (Detectron2@v0.5 is referenced)
- does it work with slavic characters? Slovenian or Croatian languages (š,č,ć,ž etc.).  pytesseract is referenced and 
  Tesseract has slavic libraries and support OCR of Croatian and Slovenian languages.

**Comment by VikParuchuri** [comment]
Closing this in favor of #12
