### ISSUE TITLE
Extraction from 2 column text, marker mixes left and right colum text paragraphs.

### ISSUE THREAD

**Issue by nekiee13** [VikParuchuri/marker#50]
I've installed marker using wsl under Win11. Tested it in English, Croatian an Slovenian - it makes perfect job removing headers and footers, sidelines etc. 

It struggles with :
- text bullets (I can fix that easily by hand or with regex if required) and 
- with 2 column text - it mixes paragraphs from left and right column - not easily resolvable (reading unsolvable, for me at least). 

Do you have any idea why is this happening or how to fix it? 

I attached Test pdf file, in case you want to check output yourself.
[pdfTestEN.pdf](https://github.com/VikParuchuri/marker/files/13762674/pdfTestEN.pdf)
Test pdf file is created with LibreOffice & Microsoft Print to Pdf.

**Comment by VikParuchuri** [comment]
Thanks for the test case.  I'll look into this.  The ordering model should figure out the column count, but it may be misclassifying these pages.

**Comment by nekiee13** [comment]
Just to add, in some instances (not always) some paragraphs are also omitted from output md.

**Comment by nekiee13** [comment]
Update:
I did some more testing, and it seems that the issue with LayoutLMv3 is related to pdf format protocol. With pdf 2.0 it seems to be working much better (fine/correct). "MS Print to pdf" uses pdf 1.7. 
I'll do some more testing, but it seems that pdf format is causing the issue. 
Possible?

**Comment by VikParuchuri** [comment]
I honestly haven't looked into PDF format versions, so I don't know if that is it.  That's an interesting find, though.

It may also be related to whether the data in the pdf was scanned/ocred or if it is a "digital" pdf created along with the text.  Digital PDFs would have higher quality bounding boxes and images.

**Comment by VikParuchuri** [comment]
I'm currently working on a better way to detect columns that might be useful for this

**Comment by paulcx** [comment]
same issue here.

**Comment by tifa365** [comment]
Same problem on a 2-column pdf:

- with 2 column text - it mixes paragraphs from left and right column

**Comment by cahya-wirawan** [comment]
Hi, I have also the same problem. Here is the link to the pdf files:

1. https://www.datenschutz.rlp.de/fileadmin/lfdi/Dokumente/Orientierungshilfen/DSK_KPNr_2_Sanktionen.pdf
2.  https://www.datenschutz.rlp.de/fileadmin/lfdi/Dokumente/Orientierungshilfen/DSK_KPNr_3_Werbung.pdf

The other 18 pdf files listed here https://www.datenschutz.rlp.de/de/themenfelder-themen/datenschutz-grundverordnung/kurzpapiere-zur-auslegung-der-ds-gvo/ might also have the same issues.
Thanks.

**Comment by hannah-chy** [comment]
Same problem on a 2-column pdf:

with 2 column text - it mixes paragraphs from left and right column

**Comment by cahya-wirawan** [comment]
any news about this issue?

**Comment by VikParuchuri** [comment]
This should be fixed in the new version (coming in the next couple of weeks).

**Comment by nekiee13** [comment]
Great 👍

**Comment by VikParuchuri** [comment]
Try the dev branch if you're having issues - there is better ordering implemented there, but still have to test more before merging.
