### ISSUE TITLE
Query Regarding Support for Additional Languages in Marker

### ISSUE THREAD

**Issue by yihong1120** [VikParuchuri/marker#57]
Dear Marker Maintainers,

I hope this message finds you well. I am reaching out to inquire about the current language support within Marker and the potential for expanding this to include additional languages.

Having perused the `settings.py` file, I noted that there is a provision for a selection of languages, predominantly European ones alongside a few Asian languages. However, I am particularly interested in understanding whether there are plans afoot to incorporate further languages into this impressive tool.

The utility of Marker would be significantly enhanced by the inclusion of languages such as Arabic, which possesses unique orthographic characteristics, or smaller European languages that may not have been the focus of extensive testing.

Moreover, I would be grateful for any guidance on the process of contributing to the language list. Is there a particular protocol for proposing new languages, and are there specific requirements that a language must meet to be considered for addition?

I appreciate the remarkable work that has gone into developing Marker and look forward to its continued evolution.

Best regards,
yihong1120

**Comment by VikParuchuri** [comment]
Thanks for the message!  Marker should support any language that tesseract supports right now that has left to right, top to bottom reading (unfortunately I don't think Arabic will work).  

I've been planning to grab a list of all the languages supported by tesseract, and make a json file mapping language name to tesseract id (like `"English": "eng"`).  This would enable just importing that file into `settings.py` to support any language that tesseract does.

If this is something you'd like to work on, happy to review the PR/help point you in the right direction.

**Comment by VikParuchuri** [comment]
The next version will support ~90 languages (coming in the next couple of weeks).

**Comment by EssamWisam** [comment]
Hope Arabic support comes soon.
