### ISSUE TITLE
Failed table reading

### ISSUE THREAD

**Issue by OmriNach** [VikParuchuri/marker#58]
Just tested out for the first time on one document. It failed properly reading the table. 
Also, the flow is cut off from column 1 parargraph -> column 2 paragraph if there is a table at the end, even though the paragraph continues from column 1 to 2. 

![Screen Shot 2024-01-04 at 10 41 47 AM](https://github.com/VikParuchuri/marker/assets/32659330/f088ef3b-6140-478d-a089-6a5890244425)
![Screen Shot 2024-01-04 at 10 41 37 AM](https://github.com/VikParuchuri/marker/assets/32659330/879d5687-2561-431d-89c7-037f72806af9)

**Comment by VikParuchuri** [comment]
This should be fixed in the dev branch.  Need to test before merging to master.

**Comment by VikParuchuri** [comment]
Should be fixed in https://github.com/VikParuchuri/marker/pull/116

**Comment by OmriNach** [comment]
Amazing work, looking forward to testing this out!
