### ISSUE TITLE
Make it available throught a API

### ISSUE THREAD

**Issue by DelScipio** [VikParuchuri/marker#59]
The actual implementation of marker is pretty bare bones, no way to use it easily outside just run the script. How be interesting to have an simple API call that would get the file and output the results.

**Comment by simjak** [comment]
@VikParuchuri I would like to help to host this under API, if you need DevOps help for setting it up, please let me know.

**Comment by VikParuchuri** [comment]
Hey, thanks for the suggestion.  I'm working on some other components of marker first (removing the commercial use restriction, better OCR), but this is on my list for after that.

**Comment by Chrissi2802** [comment]
Hi, there is already an API that can solve this problem. You can find more information about the API here: [DataLab API](https://www.datalab.to/). The API is also described in the repository's README.
Since the API provides the required functionality, I suggest closing this issue. @VikParuchuri

**Comment by VikParuchuri** [comment]
Thanks for the ping @Chrissi2802
