### ISSUE TITLE
Units in readme benchmark table

### ISSUE THREAD

**Issue by Blair-Johnson** [VikParuchuri/marker#62]
Thanks for making this cool project! 

The benchmarks section of the readme would be more helpful if it specified the units used when measuring time per page and accuracy. Different setups will obviously perform differently, but it would be helpful for people to understand the rough order of magnitude of the tool's speed.

**Comment by VikParuchuri** [comment]
Times are in seconds, accuracy is an alignment score indicating % alignment between chunks of a reference document and chunks of the prediction.  Alignment is calculated using edit distance, so a higher % means the reference and prediction were more similar.

This is in the charts, but not in the tables.
