### ISSUE TITLE
error in the example text

### ISSUE THREAD

**Issue by Wladefant** [VikParuchuri/marker#67]
![image](https://github.com/VikParuchuri/marker/assets/79611093/11a6428f-1f5d-4dbd-92f8-6cf89e64c69b)

![image](https://github.com/VikParuchuri/marker/assets/79611093/8cd7e04e-8e7e-4a17-92e5-b555fec72237)

VikParuchuri, for reference for a future model

**Comment by VikParuchuri** [comment]
Thanks - line endings aren't always detected properly.  Hoping to improve that soon.
