### ISSUE TITLE
convert.py: self.TORCH_DEVICE TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by mrticker** [VikParuchuri/marker#75]
`convert_single.py` works for me. 

`convert.py` throws this error:

```
[1Aspecial_tokens_map.json: 100%|----------| 267/267 [00:00<00:00, 521kB/s]
Traceback (most recent call last):
  File "/marker/convert.py", line 19, in <module>
    @ray.remote(num_cpus=settings.RAY_CORES_PER_WORKER, num_gpus=.05 if settings.CUDA else 0)
  File "/marker/marker/settings.py", line 115, in CUDA
    return "cuda" in self.TORCH_DEVICE
TypeError: argument of type 'NoneType' is not iterable
```
There is a GPU and CUDA available.

**Comment by lunol** [comment]
Same issue here on a Macbook with M1 chip and running the script from a VEnv.

**Comment by lunol** [comment]
> `convert_single.py` works for me.
> 
> `convert.py` throws this error:
> 
> ```
> [1Aspecial_tokens_map.json: 100%|----------| 267/267 [00:00<00:00, 521kB/s]
> Traceback (most recent call last):
>   File "/marker/convert.py", line 19, in <module>
>     @ray.remote(num_cpus=settings.RAY_CORES_PER_WORKER, num_gpus=.05 if settings.CUDA else 0)
>   File "/marker/marker/settings.py", line 115, in CUDA
>     return "cuda" in self.TORCH_DEVICE
> TypeError: argument of type 'NoneType' is not iterable
> ```



> Same issue here on a Macbook with M1 chip and running the script from a VEnv.

I've just fixed it by changing the settings file located at the marker folder:
---
class Settings(BaseSettings):
    # General
    TORCH_DEVICE: Optional[str] = "cpu"

    @computed_field
    @property
    def TORCH_DEVICE_MODEL(self) -> str:
        if self.TORCH_DEVICE is not None:
            return self.TORCH_DEVICE

        if torch.cuda.is_available():
            return "cuda"

        if torch.backends.mps.is_available():
            return "mps"

        return "cpu"
---

**Comment by guialfaro053** [comment]
You could try also doing `TORCH_DEVICE="coda"` in your local.env file.

**Comment by saria-lh** [comment]
> You could try also doing `TORCH_DEVICE="coda"` in your local.env file.
 `TORCH_DEVICE="cuda"` . Worked like a charm

**Comment by saria-lh** [comment]
> You could try also doing `TORCH_DEVICE="coda"` in your local.env file.

`TORCH_DEVICE="cuda"`. Worked like a charm.
