### ISSUE TITLE
Token indices sequence length is longer than the specified maximum sequence length for this model (395 > 384)

### ISSUE THREAD

**Issue by mrticker** [VikParuchuri/marker#78]
`Token indices sequence length is longer than the specified maximum sequence length for this model (395 > 384). Running this sequence through the model will result in indexing errors`

I get this warning relatively often when converting arxiv papers. Examples: 
https://arxiv.org/abs/2001.04451
https://arxiv.org/abs/2301.10226
https://arxiv.org/abs/2002.05770

**Comment by yasyf** [comment]
+1! Same on various biorxiv papers

**Comment by moxi000** [comment]
+1, same problem

**Comment by VikParuchuri** [comment]
This should be fine - texify can work above this length.  (it's a warning, not an error)
