### ISSUE TITLE
Issue with installation requirements (pydantic_settings)

### ISSUE THREAD

**Issue by JamMaster1999** [VikParuchuri/marker#81]
Hello I have tried installing the library requirements using the following command: 
`xargs brew install < scripts/install/brew-requirements.txt` but I am getting multiple errors of missing libraries the latest being about `ModuleNotFoundError: No module named 'pydantic_settings'`
Please help.

**Comment by VikParuchuri** [comment]
Did you use `poetry install` to install the python deps?
