### ISSUE TITLE
Issue with indexer

### ISSUE THREAD

**Issue by akaler727** [VikParuchuri/marker#82]
Hello when I execute the convert_singlet.py with mac
`ModuleNotFoundError: No module named 'indexer '`

my local.env:
TESSDATA_PREFIX=/usr/local/Cellar/tesseract

The contents of brew-requirements.txt have been installed

Please tell me what else needs to be changed. Looking forward to your reply
thank you

**Comment by luoxuan0908** [comment]
I have also encountered the same situation.

**Comment by wenkaier** [comment]
I have also encountered the same situation.

**Comment by wenkaier** [comment]
pip install pyspellchecker not spellchecker @akaler727

**Comment by VikParuchuri** [comment]
The spellchecker dependency will be removed in the next version, so this shouldn't be an issue anymore soon.
