### ISSUE TITLE
Lock file is out of date

### ISSUE THREAD

**Issue by tekumara** [VikParuchuri/marker#94]
On macOS running from commit [ad6c97c](https://github.com/VikParuchuri/marker/commit/ad6c97ca916084b225cc3319637449efbd4b0cb6)
```
❯ poetry install
Installing dependencies from lock file

pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.
```

**Comment by thawn** [comment]
same here on ubuntu 22.04 LTS

**Comment by amuricys** [comment]
Came here to say this. on macOS 13.5.2

**Comment by VikParuchuri** [comment]
Will fix this in the next version.
