### ISSUE TITLE
Illegal hardware instruction

### ISSUE THREAD

**Issue by amuricys** [VikParuchuri/marker#99]
Might have to do with #97, no idea. I had to downgrade my Python version and install Ray globally, then get into the shell and try converting a single file. Other than that I just followed the README. I'm getting the following:

(marker-pdf-py3.12) ➜  marker git:(master) ✗ python3 convert_single.py reservoir-tikhonov.pdf reservoir-tikhonov.md
Loaded texify model to mps with torch.float16 dtype
[1]    48315 illegal hardware instruction  python3 convert_single.py

Got this with another PDF too.

**Comment by amuricys** [comment]
After fiddling with brew installations for a while, it seems that one of the dependencies (ocrmypdf) depends on python 3.12, which is not supported by ray. Dependency hell I guess

```
brew install ocrmypdf libmagic tesseract tesseract-lang
==> Downloading https://ghcr.io/v2/homebrew/core/ocrmypdf/manifests/16.1.2
##################################################################### 100.0%
==> Fetching dependencies for ocrmypdf: python@3.12, glib, cairo, harfbuzz, libraqm, pillow, img2pdf, pango, tesseract, libass, ffmpeg and unpaper
```

**Comment by halghasra** [comment]
I'm also getting this issue and it is doing my head in!! I've been fiddling with brew for hours and days and I'm still getting the same error every single time! @VikParuchuri any insights on this issue?

zsh: illegal hardware instruction  python convert_single.py  docfiles/destination/output.md

**Comment by VikParuchuri** [comment]
This will be fixed in the new version (to be merged shortly).  I removed ocrmypdf as a required dependency, and bumped the ray version.
